<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" ignored="15" total="21" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="11775" started-at="2019-12-12T07:27:27Z" finished-at="2019-12-12T07:27:39Z">
    <groups>
    </groups>
    <test name="BGG_Stage" duration-ms="11775" started-at="2019-12-12T07:27:27Z" finished-at="2019-12-12T07:27:39Z">
      <class name="com.cai.qa.bg.testScripts.BGG.VerifyFooterLinks">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.VerifyFooterLinks@22a637e7]" name="beforeClass" is-config="true" duration-ms="1" started-at="2019-12-12T12:57:36Z" finished-at="2019-12-12T12:57:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="Launch()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.VerifyFooterLinks@22a637e7]" name="Launch" duration-ms="742" started-at="2019-12-12T12:57:36Z" finished-at="2019-12-12T12:57:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Bluegreen Getaways | Vacation Packages] but found [Maintenance | Bluegreen Vacations]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Bluegreen Getaways | Vacation Packages] but found [Maintenance | Bluegreen Vacations]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.cai.qa.bg.testScripts.BGG.VerifyFooterLinks.Launch(VerifyFooterLinks.java:23)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launch -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.cai.qa.bg.testScripts.BGG.VerifyFooterLinks@22a637e7]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-12-12T12:57:36Z" finished-at="2019-12-12T12:57:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Launch status=FAILURE method=VerifyFooterLinks.Launch()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.VerifyFooterLinks@22a637e7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.cai.qa.bg.testScripts.BGG.VerifyFooterLinks -->
      <class name="com.cai.qa.bg.testScripts.BGG.CreateBGGetawayPackage_Resort">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.CreateBGGetawayPackage_Resort@69b2283a]" name="beforeClass" is-config="true" duration-ms="0" started-at="2019-12-12T12:57:35Z" finished-at="2019-12-12T12:57:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="Launch()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.CreateBGGetawayPackage_Resort@69b2283a]" name="Launch" duration-ms="680" started-at="2019-12-12T12:57:35Z" finished-at="2019-12-12T12:57:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Bluegreen Getaways | Vacation Packages] but found [Maintenance | Bluegreen Vacations]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Bluegreen Getaways | Vacation Packages] but found [Maintenance | Bluegreen Vacations]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.cai.qa.bg.testScripts.BGG.CreateBGGetawayPackage_Resort.Launch(CreateBGGetawayPackage_Resort.java:36)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launch -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.cai.qa.bg.testScripts.BGG.CreateBGGetawayPackage_Resort@69b2283a]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-12-12T12:57:36Z" finished-at="2019-12-12T12:57:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Launch status=FAILURE method=CreateBGGetawayPackage_Resort.Launch()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.CreateBGGetawayPackage_Resort@69b2283a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.cai.qa.bg.testScripts.BGG.CreateBGGetawayPackage_Resort -->
      <class name="com.cai.qa.bg.testScripts.BGG.VerifyHeaderLinks">
        <test-method status="FAIL" signature="Launch()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.VerifyHeaderLinks@6fe7aac8]" name="Launch" duration-ms="638" started-at="2019-12-12T12:57:36Z" finished-at="2019-12-12T12:57:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Bluegreen Getaways | Vacation Packages] but found [Maintenance | Bluegreen Vacations]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Bluegreen Getaways | Vacation Packages] but found [Maintenance | Bluegreen Vacations]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.cai.qa.bg.testScripts.BGG.VerifyHeaderLinks.Launch(VerifyHeaderLinks.java:31)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launch -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.VerifyHeaderLinks@6fe7aac8]" name="beforeClass" is-config="true" duration-ms="0" started-at="2019-12-12T12:57:36Z" finished-at="2019-12-12T12:57:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.cai.qa.bg.testScripts.BGG.VerifyHeaderLinks@6fe7aac8]" name="afterMethod" is-config="true" duration-ms="1" started-at="2019-12-12T12:57:37Z" finished-at="2019-12-12T12:57:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Launch status=FAILURE method=VerifyHeaderLinks.Launch()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.VerifyHeaderLinks@6fe7aac8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.cai.qa.bg.testScripts.BGG.VerifyHeaderLinks -->
      <class name="com.cai.qa.bg.testScripts.BGG.CreateBGGetawayPackage_Hotel">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.CreateBGGetawayPackage_Hotel@bef2d72]" name="beforeSuite" is-config="true" duration-ms="1948" started-at="2019-12-12T12:57:25Z" finished-at="2019-12-12T12:57:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.CreateBGGetawayPackage_Hotel@bef2d72]" name="beforeTest" is-config="true" duration-ms="22" started-at="2019-12-12T12:57:27Z" finished-at="2019-12-12T12:57:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.CreateBGGetawayPackage_Hotel@bef2d72]" name="beforeClass" is-config="true" duration-ms="77" started-at="2019-12-12T12:57:27Z" finished-at="2019-12-12T12:57:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="Launch()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.CreateBGGetawayPackage_Hotel@bef2d72]" name="Launch" duration-ms="7638" started-at="2019-12-12T12:57:27Z" finished-at="2019-12-12T12:57:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Bluegreen Getaways | Vacation Packages] but found [Maintenance | Bluegreen Vacations]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Bluegreen Getaways | Vacation Packages] but found [Maintenance | Bluegreen Vacations]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.cai.qa.bg.testScripts.BGG.CreateBGGetawayPackage_Hotel.Launch(CreateBGGetawayPackage_Hotel.java:47)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launch -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.cai.qa.bg.testScripts.BGG.CreateBGGetawayPackage_Hotel@bef2d72]" name="afterMethod" is-config="true" duration-ms="1" started-at="2019-12-12T12:57:35Z" finished-at="2019-12-12T12:57:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Launch status=FAILURE method=CreateBGGetawayPackage_Hotel.Launch()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.CreateBGGetawayPackage_Hotel@bef2d72] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.CreateBGGetawayPackage_Hotel@bef2d72]" name="afterTest" is-config="true" duration-ms="633" started-at="2019-12-12T12:57:38Z" finished-at="2019-12-12T12:57:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.cai.qa.bg.testScripts.BGG.CreateBGGetawayPackage_Hotel -->
      <class name="com.cai.qa.bg.testScripts.BGG.VerifyYoutubeVideoAndTabsAssociated">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.VerifyYoutubeVideoAndTabsAssociated@659a969b]" name="beforeClass" is-config="true" duration-ms="2" started-at="2019-12-12T12:57:38Z" finished-at="2019-12-12T12:57:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="Launch()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.VerifyYoutubeVideoAndTabsAssociated@659a969b]" name="Launch" duration-ms="643" started-at="2019-12-12T12:57:38Z" finished-at="2019-12-12T12:57:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Bluegreen Getaways | Vacation Packages] but found [Maintenance | Bluegreen Vacations]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Bluegreen Getaways | Vacation Packages] but found [Maintenance | Bluegreen Vacations]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.cai.qa.bg.testScripts.BGG.VerifyYoutubeVideoAndTabsAssociated.Launch(VerifyYoutubeVideoAndTabsAssociated.java:32)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launch -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.cai.qa.bg.testScripts.BGG.VerifyYoutubeVideoAndTabsAssociated@659a969b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-12-12T12:57:38Z" finished-at="2019-12-12T12:57:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Launch status=FAILURE method=VerifyYoutubeVideoAndTabsAssociated.Launch()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.VerifyYoutubeVideoAndTabsAssociated@659a969b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.cai.qa.bg.testScripts.BGG.VerifyYoutubeVideoAndTabsAssociated -->
      <class name="com.cai.qa.bg.testScripts.BGG.VerifySearchFunctionality">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.VerifySearchFunctionality@1d119efb]" name="beforeClass" is-config="true" duration-ms="1" started-at="2019-12-12T12:57:37Z" finished-at="2019-12-12T12:57:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="Launch()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.VerifySearchFunctionality@1d119efb]" name="Launch" duration-ms="666" started-at="2019-12-12T12:57:37Z" finished-at="2019-12-12T12:57:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Bluegreen Getaways | Vacation Packages] but found [Maintenance | Bluegreen Vacations]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Bluegreen Getaways | Vacation Packages] but found [Maintenance | Bluegreen Vacations]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.cai.qa.bg.testScripts.BGG.VerifySearchFunctionality.Launch(VerifySearchFunctionality.java:23)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launch -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.cai.qa.bg.testScripts.BGG.VerifySearchFunctionality@1d119efb]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-12-12T12:57:38Z" finished-at="2019-12-12T12:57:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Launch status=FAILURE method=VerifySearchFunctionality.Launch()[pri:0, instance:com.cai.qa.bg.testScripts.BGG.VerifySearchFunctionality@1d119efb] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.cai.qa.bg.testScripts.BGG.VerifySearchFunctionality -->
    </test> <!-- BGG_Stage -->
  </suite> <!-- Suite -->
</testng-results>
